### ISSUE TITLE
multi line with bar and

### ISSUE THREAD

**Issue by Pascal66** [mozilla/metrics-graphics#345]
timestamp in unix format instead YY-mm-dd

Didnt find a way to do both 

And linked data table with graphics

Thank for this nice work

**Comment by almossawi** [comment]
In order to override the x-axis time format, take a look at [xax_format](https://github.com/mozilla/metrics-graphics/wiki/Axes#xax_format). To override the rollover text, take a look at [mouseover](https://github.com/mozilla/metrics-graphics/wiki/Graphic#mouseover). If you mean [MG.convert.date](https://github.com/mozilla/metrics-graphics/wiki/Convenience-Functions#mg-convert-date), please refer to the link on time formatting in the wiki.

**Comment by Pascal66** [comment]
I've read about convertdate. but i cant convert an unix timestamp.
