### ISSUE TITLE
Data table: plans with respect to paging, column sorting and filter

### ISSUE THREAD

**Issue by melnikovkolya** [mozilla/metrics-graphics#349]
Hi, 

we were wondering if there are any plans in the road map wrt the following items: table paging, column sorting and filtering?

**Comment by hamilton** [comment]
We are still working out the details about what exactly we want out of data tables, but

- Column sorting will likely be an element
- Pagination is a low priority for us since other libraries handle this so well
- Filtering is also a low priority for similar reasons
- The next big feature we want in data tables is _small multiples_ - being able to show graphs within cells in a nice, principled way will really make data tables stand out.

You are of course welcome to help us with an of these things! Submit a PR for review and we'll review it.
