### ISSUE TITLE
x axis smaller than the line

### ISSUE THREAD

**Issue by HoplaGeiss** [mozilla/metrics-graphics#419]
As you can see on this screenshot. My x-axis is slightly smaller than my line. How can I change this? 
For the y-axis I used `inflator: 15/10`. this doesnt seem to affect the x-axis!

![screenshot from 2015-04-28 16 09 54](https://cloud.githubusercontent.com/assets/5755785/7371432/2d8e5734-edc1-11e4-82f5-79fae109dba2.png)

**Comment by HoplaGeiss** [comment]
i just changed my data set and I have the opposite problem :P 
![screenshot from 2015-04-28 17 28 26](https://cloud.githubusercontent.com/assets/5755785/7373342/163a3962-edcc-11e4-9255-2b9f606b5f53.png)

This time my x-axis doesnt go all the way to the left!

**Comment by almossawi** [comment]
That is by design. The axes cover the [range of the auto-generated ticks](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/x_axis.js#L343).

To force the x-axis to start at the left-most edge, i.e. the first data point, you can set [xax_start_at_min](https://github.com/mozilla/metrics-graphics/wiki/Axes#xax_start_at_min) to true.

**Comment by HoplaGeiss** [comment]
Perfect! Thanks. Also to make x-axis larger I used `max_x`
