### ISSUE TITLE
Add option for 24-hour clock countries

### ISSUE THREAD

**Issue by Dragony** [mozilla/metrics-graphics#436]
Hi!

I'm from Europe and we use the 24 hours system. Sadly the lib doesn't display the time on the X axis correctly when in a zone with the 24 hour system.

Screenshot from the example [page](http://metricsgraphicsjs.org/examples.htm#auto-time-formatting):
![time](https://cloud.githubusercontent.com/assets/465941/7778981/be8caafc-00d0-11e5-85d5-118713f3fcf6.png)

Greetings

**Comment by almossawi** [comment]
Hi there, Keep in mind that the labels along the x-axis show minutes and seconds, whereas the hour appears below the first tick.

Due to [this line](https://github.com/mozilla/metrics-graphics/blob/master/dist/metricsgraphics.js#L1654), the hour is formatted using a 12-hour clock and appended with either AM and PM. To change that, use an [alternative directive](https://github.com/mbostock/d3/wiki/Time-Formatting), e.g. for a 24-hour clock:

```javascript
d3.time.format('%H');
```

You'll find the corresponding line under [js/common/x_axis.js](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/x_axis.js#L426)

@hamilton Is this something we'd want to provide an option for?

**Comment by hamilton** [comment]
@almossawi I think it makes sense to provide an option. What should we call it?

**Comment by Dragony** [comment]
Hey there, sorry guys. It seems logical now that i've slept over it :) Thanks for the effort! An option sounds awesome too!

**Comment by matteocontrini** [comment]
Up
