### ISSUE TITLE
Need help with lots of data over a small time range

### ISSUE THREAD

**Issue by christinalau** [mozilla/metrics-graphics#440]
Hi, I am wondering if you can help me out here as I am new to using this:

I am trying to use it to graph a lot of data ( > 2000) over less than a few days, and I found that when the number of data gets large, the performance is very slow when I hover over the graph.

![performance](https://cloud.githubusercontent.com/assets/5726085/7922131/1bab03c4-0878-11e5-8532-e929e83e77e4.png)

Is this a valid use case for this package? Maybe I need to specify more parameters, and if yes, what are they? Thanks for any help...

**Comment by almossawi** [comment]
Hi there, Kindly refer to #439 as the reply there will likely be pertinent.

Since you're working with SVG, you'll find that you take a potential performance hit any time you have a dataset whose maximum size is arbitrary. Consider smoothing your data or using zooming, where the general principal is that you show finer granularity as you zoom in.

Hope that helps.
