### ISSUE TITLE
custom_line_color_map doesn't clean up old lines

### ISSUE THREAD

**Issue by yonester** [mozilla/metrics-graphics#474]
Paste the following in the [interactive demo](http://metricsgraphicsjs.org/interactive-demo.htm) page and hit **run**:

```js
var data = d3.range(2).map(function() {
  return d3.range(10).map(function(d) {
    return { year: 2000 + d, value: Math.floor(Math.random() * 100) };
  });
});

MG.data_graphic({
  data: data,
  width: 400,
  height: 250,
  target: ".result",
  x_accessor: "year",
  y_accessor: "value"
});
```

Then add this to the graphic data and hit **run** again.

```js
custom_line_color_map: [1, 3]
```

Notice that three lines appear because one of the lines never gets cleaned up from the old data. This is relevant when the `custom_line_color_map` argument is used differently depending on the incoming data. For example,

```js
custom_line_color_map: (data.length === 2) ? [1, 2] : [2, 3, 4]
```

**Comment by almossawi** [comment]
Thanks, targeting 2.7.

**Comment by almossawi** [comment]
You'll need to set [max_data_size](https://github.com/mozilla/metrics-graphics/wiki/Graphic#max_data_size) to avoid zombie lines when you specify a value in custom_line_color_map that's greater than the number of lines you're plotting. So in your case,

```javascript
var data = d3.range(2).map(function() {
  return d3.range(10).map(function(d) {
    return { year: 2000 + d, value: Math.floor(Math.random() * 100) };
  });
});

MG.data_graphic({
  data: data,
  width: 400,
  height: 250,
  target: ".result",
  x_accessor: "year",
  y_accessor: "value",
  custom_line_color_map: [1, 3],
  max_data_size: 3
});
```

Apologies for not spotting this earlier--it was an oversight on my part. The second option is due to [this block](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/init.js#L132).

**Comment by eugene-p** [comment]
Still a bug in my book. Using useless parameter to do filtering on a class name. Should be re-opened. 
Can it be fixed as part of https://github.com/mozilla/metrics-graphics/issues/546 ?
