### ISSUE TITLE
Exception on 2nd call to MG.data_graphic when y_accessor is array (for multi-line charts)

### ISSUE THREAD

**Issue by gelbal** [mozilla/metrics-graphics#488]
Hello there,

I encountered an issue very similar to [#401](https://github.com/mozilla/metrics-graphics/issues/401)

When the chart option's y_accessor is an array, calling MG.data_graphic the 2nd time causes an error. The chart update doesn't happen and chart gets broken altogether. 

The error is 
```
Error: Invalid value for <path> attribute d="null" 
```

Sample code to illustrate:

```javascript
var data = [];

var options = {
    description: 'New data is shown as it comes in',
    title: 'Realtime updates',
    max_y: 120,
    xax_start_at_min: true,
    transition_on_update: true,
    y_extended_ticks: true,
    interpolate: 'linear',
    x_accessor: 'date',
    y_accessor: ['value1', 'value2'],
    target: '.result'
 };

 setInterval(function () {
    var date = new Date();

    //set min and max when some data is present
    if (data.length > 6) {
        options.min_x = new Date(+data[data.length - 3].date);
        options.max_x = new Date(+options.min_x + 6000);
    }

    // add new value
    data.push({
        date: date,
        value1: Math.random() * (100 - 0) + 0,
        value2: Math.random() * (100 - 0) + 0
    });
    options.data = data;
    MG.data_graphic(options);
}, 1000);

```

Btw, there is no error when I use the alternative y_accessor method to create multi-line charts (data object as array of arrays).

**Comment by almossawi** [comment]
The error should be fixed. Thanks for reporting it, and apologies for the late reply.

Because multi-y-accessors get [transformed internally](https://github.com/mozilla/metrics-graphics/blob/master/src/js/misc/process.js#L42), you can do one of two things in your case:

1) Reset y_accessor before calling MG.data_graphic:

```javascript
...
options.y_accessor = ['value1', 'value2'];
options.data = data;
MG.data_graphic(options);
...
```

2) Clone your _options_ object before calling MG.data_graphic:

```javascript
MG.data_graphic(MG.clone(options));
```

Feel free to reopen the issue if the problem persists.
