### ISSUE TITLE
year markers are pushed a little too far down

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#531]
needs the ``dy`` for ``text.mg-year-marker`` to be around ``.20em`` not ``.50em``. Will naturally get cut off a bit in its current state with the removed small-text option.

**Comment by almossawi** [comment]
@hamilton The 0.2em was so that it doesn't collide with the axis labels when using the new _accessible_ style.

With 0.5em:
<img width="661" alt="screen shot 2015-10-27 at 1 31 37 pm" src="https://cloud.githubusercontent.com/assets/980049/10771658/2846af88-7caf-11e5-8b1f-c7fdc2d4dc46.png">

With 0.2em:
<img width="628" alt="screen shot 2015-10-27 at 1 34 22 pm" src="https://cloud.githubusercontent.com/assets/980049/10771707/7c7684fc-7caf-11e5-9c20-211fb71ff822.png">


Also, there's a slight inconsistency between Webkit and Firefox when positioning with dy, I've noticed.

**Comment by hamilton** [comment]
@almossawi Interesting.The .50em seems to get cut off in a bunch of the normal examples. What do you think is the writing way of going about this bit? I'm testing in FF so that might also explain the issue.

![screen shot 2015-10-27 at 1 37 07 pm](https://cloud.githubusercontent.com/assets/95735/10771764/da54388a-7caf-11e5-9412-861f72a86cb0.png)

**Comment by almossawi** [comment]
@hamilton Hmm.. are you using Nightly? This is how it looks on Beta:

<img width="599" alt="screen shot 2015-10-27 at 1 45 19 pm" src="https://cloud.githubusercontent.com/assets/980049/10772006/fd5d964a-7cb0-11e5-8f52-d3f8ab545e91.png">

I tested it in all possible combinations to make sure the label doesn't get clipped.

**Comment by hamilton** [comment]
Very odd. I'm on 40.0b8.

![screen shot 2015-10-27 at 1 58 03 pm](https://cloud.githubusercontent.com/assets/95735/10772323/ca5debf8-7cb2-11e5-86bc-7d71dd442085.png)

**Comment by hamilton** [comment]
Wow - it seems to only be an issue on old monitors, not my laptop. Going to revert the change. Note to self: never trust an external monitor from 2008.
