### ISSUE TITLE
Adopt a consistent coding style

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#534]
We have some inconsistencies in the code that might impair readability. Consider complying with a [JS style guide](https://github.com/airbnb/javascript/tree/master/es5).

**Comment by hamilton** [comment]
I like this as an overarching issue. I propose that we follow a slightly modified model led by #533:

1. decompose problematic code
2. refactor according to best practices within components
3. write tests

**Comment by almossawi** [comment]
I meant the focus for this issue to be strictly style, as we have inconsistencies in names, tabs, spaces, etc. I'd be happy to close this issue and track it in #533 if that makes more sense.

**Comment by hamilton** [comment]
I think I'm being a little too vague. I like this issue because I think it is necessary, but I propose that we expand the issue to make style one part of a broader task of cleaning up, which should include decomposition (which that style guide does not cover).

#533 focuses on one particular component of MG, and (now) seeks to decompose, refactor, and test. I think tackling this issue by working on component issues is a good way of tackling this for v2.8 (which #533 does). So, for instance, when we want to clean up ``x_axis.js``we can create an issue for the refactoring, style, and test coverage of that component.

Sorry for wordiness - its my birthday so I don't have time to write a shorter comment :)

**Comment by almossawi** [comment]
Sounds good :)

**Comment by brylie** [comment]
This task could be used to track the inclusion of a JSCS and linter configuration files in the project. JSCS can be used to define coding standard for the project while a linter can catch other issues.

# Reference
* [ESLint](http://eslint.org/)
* [JSCS](http://jscs.info/)
* [JSHint](http://jshint.com/)

**Comment by mouradmourafiq** [comment]
I would suggest also to reduce the nesting level. In some files the nesting level is so deep that is so difficult to follow the logic.

**Comment by brylie** [comment]
What coding standard will the project adopt? E.g. JS Happiness? I am available to assist with linting, commenting, and cleanup, once a coding standard has been defined (e.g. via JSCS) or decided upon.

**Comment by hamilton** [comment]
@mouradmourafiq that is precisely the main task here, and is definitely an embarrassing headache for us as well.

@brylie We are using semistandard as our coding standard.

**Comment by brylie** [comment]
OK, the coding standard should probably be mentioned in the contributing section of README. Also, it is common for projects to have a CONTRIBUTING.md file, and Github looks for this file as well.

**Comment by hamilton** [comment]
This will not be finished by 2.8's release, even though we've made great progress this quarter making the code slightly less impossible to read. Pushing to 2.9.
