### ISSUE TITLE
When custom color are provided, lines aren't properly updated

### ISSUE THREAD

**Issue by shmul** [mozilla/metrics-graphics#546]
Hi,

Using version 2.7.0, I added a custom color to my graph. The graph is refreshed every couple of minutes, and oddly, only when a custom color is specified, the previous line isn't properly transitioned and it is left there, unerased. The attached screen capture shows the effect after 3 or so time the data was updated.If however no color option is provided, everything works great.

I noticed the code has does have a comment saying "UNFINISHED - if we have args.colors, color the line appropriately." . Any idea when you would get to handling it?

Cheers,
Shmul

![mg_colored_line](https://cloud.githubusercontent.com/assets/701036/11066887/a6bfa846-87d2-11e5-8a6f-92a5a66f3f79.png)

**Comment by hamilton** [comment]
Hi - that's unfortunate. We had to change a lot under the hood to decouple some selectors with colors, so it would appear that the work is not complete. We'll get to this before 2.8 is out, probably on the sooner side since this is a bug. Thanks for the issue - points us to another set of tests we need to consider.
