### ISSUE TITLE
separate scale generation from axis drawing

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#630]
The internals of MG reflect a dramatic battle between "getting it to work quickly" and "preparing for the future." Look no further than the tattered remains of the axis code. We've bolted the scale generation to the axis drawing, which upon even simple long-term thought would crumble. After all, we have color, size, and other generic, non-positional data to cast upon a range of values. This is inelegant, unmaintainable, and depressing.

So the goal is to:

- [x]  pull out the scale generation code, and create a new piece called ``scales.js``
- [x]  clean up the axis drawing code to be uniform for the x and y axis

**Comment by tlatorre-uchicago** [comment]
It would also be nice to be able to specify the x axis scale directly to be used in tick generation, or alternatively to specify the ticks directly.

My use case is this. I want to display the series in the local time where the server is located, but the metrics graphics API uses the date format which is time zone agnostic. I have fixed this problem elsewhere by creating my own d3.time.scale like object whose ticks() function returns ticks spaced nicely in a given timezone and the tickFormat() function returns a time format which displays the times in the other time zone.

Currently, I can use this scale to produce the tick formatter for the line chart, but since the ticks are spaced uniformly in my local time zone the formatter looks weird. For example, if the scale is a month long, the ticks are generated on day boundaries in my local time, but this causes all of the ticks to be formatted as "1 AM".

**Comment by hamilton** [comment]
@tlatorre-uchicago if this is still an issue, can you open a new one with this in it? I am going to close this one.

**Comment by lucs100** [comment]
@tlatorre-uchicago I was able to fix a similar issue on what I assume is the same repository you were working on (I'm a student on SNO+ working on minard). It's not quite the same thing but sheds some light on something I had trouble finding documentation on and I thought it was funny I got led back here looking for help. 

Defining tickFormat() is done in a way that seems to conflict with the documentation on https://metricsgraphicsjs.org/mg-api - inside `dparams` I defined this property:

```
xax_count: 3,
xax_format: function(tick) {
        return moment.unix(tick).format("MMM Do YYYY HH:mm:SS")
    },
```
